----
   title: "Spotify"
   author: "Joel Soroos"
   date: "March 9, 2020"
   output: pdf_document
---

### 1. Activate Spotify connection
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library (spotifyr)
   library (janitor) 

   access_token <- get_spotify_access_token(
      client_id=Sys.getenv("SPOTIFY_CLIENT_ID"),
      client_secret=Sys.getenv("SPOTIFY_CLIENT_SECRET")
      )
   
   my_id <- Sys.getenv("SPOTIFY_USER_ID")
   #my_plists <- get_user_playlists(my_id)
```


### 2. source favorite tracks
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library (tidyverse)
   library (ggrepel)
   library (ggdark)

   favorite_tracks <-
     ceiling(get_my_saved_tracks(include_meta_info = TRUE)[['total']] / 50) %>%
     seq() %>%
     map(function(x) {
       get_my_saved_tracks(
          limit = 50, offset = (x - 1) * 50)
         }) %>% 
     reduce (rbind) %>%
     unnest (track.artists)
   
   #remove duplicate tracks by including first named artist only
   favorite_tracks_unique <- favorite_tracks %>%
      distinct (track.id) %>%
      pull (track.id)
```


### 3. add audio features to favorite tracks
```{r}

   favorite_tracks_features <-get_track_audio_features (favorite_tracks_unique) %>%
   #See definitions here: #https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md
      right_join(favorite_tracks, by = c("id" = "track.id")) %>%
      rename (
         artist.name = name,
         popularity = track.popularity
         ) %>%
      mutate (
         duration_min = duration_ms / 1000 / 60,
         country = str_extract(track.external_ids.isrc, "^.{2}"),
         track.name = ifelse (str_length (track.name) <= 20, track.name, str_extract(track.name, "^.{20}")),
         country = recode (country, "QM" = "US", "QZ" = "US")
         ) %>%
      select (artist.name, track.name, danceability, energy, valence, tempo, popularity, duration_min, country) %>%
      distinct (track.name, .keep_all = T)
```


### 4. visualize
```{r}
 
  ggplot (favorite_tracks_features, aes (x = valence, y = tempo, label = track.name)) +
      geom_point () +
      geom_label_repel(
         data = favorite_tracks_features %>% 
            filter (
               tempo > 175 |
               tempo < 85 |
               valence > .90 |
               valence < .25
               ),
         size = 2
         ) +
      theme(
            plot.title = element_text(hjust = 0.5, vjust = 0, size = 15, face = "bold", color = "#CC1100", margin = margin (0,0,20,0)),
            plot.caption = element_text (hjust = 1.0, size = 8, face = "plain", margin = margin (20,0,0,0)),
            plot.caption.position = "plot",
            axis.text = element_text(hjust = 0, vjust = 0, size = 9),
            #panel.grid.major = element_line(color = "grey1", size = 1),
            panel.grid.minor = element_blank()
            ) +
      labs(
         title = "My Favorite Tracks",
         caption = "Visualization: Joel Soroos @soroosj  |  Data: Spotify API",
         x = "Valence",
         y = "Tempo"
         ) +
      ggsave("songs.png")
```


5.  Visualize - bar chart (one variable)
```{r}
 
 favorite_tracks_features %>%
      arrange (-tempo) %>%
      slice (
         1:5, 
         (n()-4):n()
         ) %>%
      mutate (bar_color = ifelse (tempo > median (tempo), "Darkgreen", "Red")) %>%
      ggplot (aes (x = reorder (track.name, tempo), y = tempo, label = round(tempo,0)), size = 1) +
         geom_col (aes(fill = I(bar_color))) + 
         geom_text (
            position = position_stack(vjust = 0.96),
            color = "white"
         ) +
         geom_text(
            aes(label=track.name),
            position = position_stack(vjust = 0.02),
            color = "white", hjust = 0
            ) +
         coord_flip () +
         theme(
               plot.title = element_text(hjust = 0.5, size = 15, face = "bold", color = "#CC1100"),
               axis.text = element_blank (), 
               axis.title = element_blank(),
               axis.ticks = element_blank (),
               panel.grid = element_blank(),
               panel.background = element_blank()
               ) +
         labs(
            title = "Tempo"
            ) +
         ggsave("tempo.png")
```


6.  Visualize - bar chart (multiple variables)
```{r}

   library (glue)
 
   #https://stackoverflow.com/questions/22309285/how-to-use-a-variable-to-specify-column-name-in-ggplot/53168593#53168593
   attributes <- c("danceability", "energy", "valence", "tempo", "popularity")
   
    scatter_fun = function(attribute = tempo) {
      attribute = ensym (attribute)
      ggplot (
         data = favorite_tracks_features %>%
            arrange (-!!attribute) %>%
            slice (1:5, (n()-4):n()) %>%
            mutate (bar_color = ifelse (!!attribute > median (!!attribute), "Darkgreen", "Red")),
         aes (x = reorder (track.name, !!attribute), y = !!attribute), 
         size = 1
         ) +
         geom_col (aes(fill = I(bar_color))) + 
         geom_text (
            aes (label = round(!!attribute,0)),
            position = position_stack(vjust = 0.94),
            color = "white"
            ) + 
         geom_text(
            aes (label = track.name),
            position = position_stack(vjust = 0.02),
            color = "white", hjust = 0
            ) +
         coord_flip () +
         theme(
            plot.title = element_text(hjust = 0.5, size = 15, face = "bold", color = "black"),
            axis.text = element_blank (), 
            axis.title = element_blank(),
            axis.ticks = element_blank (),
            panel.grid = element_blank(),
            panel.background = element_blank()
            ) +
       labs(title = glue({str_to_title(attribute)}))
    }

```
