----
   title: "Spotify"
   author: "Joel Soroos"
   date: "March 9, 2020"
   output: pdf_document
---

### 1. Activate Spotify connection
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library (spotifyr)
   library (janitor) 

   access_token <- get_spotify_access_token(
      client_id=Sys.getenv("SPOTIFY_CLIENT_ID"),
      client_secret=Sys.getenv("SPOTIFY_CLIENT_SECRET")
      )
   
   my_id <- Sys.getenv("SPOTIFY_USER_ID")
   #my_plists <- get_user_playlists(my_id)
   

#https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md
```



### 2.  favorite tracks - artist count
```{r}

   library (tidyverse)

   favorite_tracks <-
     ceiling(get_my_saved_tracks(include_meta_info = TRUE)[['total']] / 50) %>%
     seq() %>%
     map(function(x) {
       get_my_saved_tracks(
          limit = 50, offset = (x - 1) * 50)
         }) %>% 
     reduce(rbind)
   
   favorite_artists <- favorite_tracks %>%
     select (track.artists) %>%
     reduce (rbind) %>%
     reduce (rbind) %>%
     select (id, name)
   
   favorite_artists %>%
      count(id, sort = TRUE) %>%
      left_join(favorite_artists, by = 'id',.) %>%
      unique() %>%
      select(-id) %>%
      arrange (-n)
```


### 3. Recently played - audio features
```{r transform, message = F, results = F, warning = F}

   library (lubridate)

   recent_raw <- get_my_recently_played(limit = 50) %>% 
      clean_names()
   
   recent <- recent_raw %>%
      mutate(
         artist_name = map_chr(track_artists, function(x) x$name[1]),
         played_at = as_datetime(played_at),
         played_at = with_tz(played_at, tzone = "America/Chicago"),
         release = year(as_datetime(track_album_release_date))
         ) %>% 
      rename (
         album_name = track_album_name
         ) %>%
      select (track_id, artist_name, track_name, release, played_at) %>%
      distinct (track_id, .keep_all = T) 

   recent_tracks <- recent %>%
      select (track_id) %>%
      pull (track_id)
   
   recent_audio_features <- get_track_audio_features (recent_tracks) %>%
      left_join(recent, by = c("id" = "track_id")) %>%
      select (artist_name: release, danceability:tempo)
```


### 4.  Top all-time songs
```{r}

   library (kableExtra)

   get_my_top_artists_or_tracks(type = 'tracks', time_range = 'long_term', limit = 50) %>% 
       mutate(artist.name = map_chr(artists, function(x) x$name[1])) %>% 
       select(name, artist.name, album.name) %>%
       kable () %>%
       kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```





